[database]
# It’s the full path to the database file
path = "$DB_PATH"

[github]
# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = "$GITHUB_ACCESS_TOKEN"

# A GitHub oauth application for this instance of homu:
app_client_id = "$GITHUB_APP_ID"
app_client_secret = "$GITHUB_APP_SECRET"

# As we create webhooks automatically, we need to know our external address
[external]
hostname = "$EXTERNAL_HOSTNAME"
scheme = "https"

[web]
# The port homu listens on
port = $WEB_PORT

[admin]
# The secret & username to call admin API
secret = "$ADMIN_SECRET"
username = "$ADMIN_USERNAME"

[quay]
# access token to use API
access_token = "$QUAY_ACCESS_TOKEN"
# namespace to create repos in
namespace = "$QUAY_NAMESPACE"
# for some API methods we can't use access token, and we need to use username/pass
# That's a shame
username = '$QUAY_USERNAME'
password = '$QUAY_PASSWORD'
