[github]

# Information for securely interacting with GitHub. These are found/generated
# under <https://github.com/settings/applications>.

# A GitHub personal access token
access_token = ""

# A GitHub oauth application for this instance of homu:
app_client_id = ""
app_client_secret = ""

[web]

# The port homu listens on
port = 54856

[admin]
# The secret & username to call admin API
secret = ''
username = 'admin'

# An example configuration for repository (there can be many of these)
[repo.NAME]

# github.com/<owner>/<name>
owner = ""
name = ""

# who has r+ rights?
reviewers = ["barosl", "graydon"]

## branch names (these settings here are the defaults)
#[repo.NAME.branch]
#
#master = "master"
#auto = "auto"
#try = "try"
#tmp = "tmp"
#rollup = "rollup"

[repo.NAME.github]

# arbitrary secret (e.g. openssl rand -hex 20)
secret = ""

## Use buildbot for running tests
#[repo.NAME.buildbot]
#
#url = ""
#secret = ""
#
#builders = ["auto-linux", "auto-mac"]
#try_builders = ["try-linux", "try-mac"]
#
#username = ""
#password = ""

## Use travis for running tests
#[repo.NAME.travis]
#
## found under <https://travis-ci.org/profile/info>.
#token = ""
